# Generated by Django 3.2 on 2024-05-16 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('academies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='academyprofessor',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academies.academy'),
        ),
        migrations.AddField(
            model_name='academyprofessor',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academies.professor'),
        ),
        migrations.AddField(
            model_name='academy',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_academy', to='users.userprofile'),
        ),
    ]
